language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install wine
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
python:
  - "2.7"
script:
  - make python.mk pyinstaller.mk
  - make dist
